### ISSUE TITLE
set trace throws exception: parser.undefined

### ISSUE THREAD

**Issue by benself** [antlr/antlr4-javascript#21]
```
Parser.js:46
	console.log("enter   " + parser.ruleNames[ctx.ruleIndex] + ", LT(1)=" + parse
	                               ^
TypeError: Cannot read property 'ruleNames' of undefined
    at TraceListener.enterEveryRule (/Users/ben/Code/gc-parser/js/src/antlr4/Parser.js:46:33)
    at /Users/ben/Code/gc-parser/js/src/antlr4/Parser.js:253:13
    at Array.map (native)
    at CSVParser.Parser.triggerEnterRuleEvent (/Users/ben/Code/gc-parser/js/src/antlr4/Parser.js:252:24)
    at CSVParser.Parser.enterRule (/Users/ben/Code/gc-parser/js/src/antlr4/Parser.js:435:8)
    at CSVParser.file (/Users/ben/Code/gc-parser/js/CSVParser.js:113:10)
    at Object.<anonymous> (/Users/ben/Code/gc-parser/js/csvtest.js:16:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

```
var chars = new antlr4.InputStream(input);
var lexer = new csv.Lexer(chars);
var tokens  = new antlr4.CommonTokenStream(lexer);
var parser = new csv.Parser(tokens);
parser.setTrace(true);
parser.buildParseTrees = true;
var tree = parser.file();
```

**Comment by benself** [comment]
Thanks!! for this.

But sorry, not quite:

```
src/antlr4/Parser.js:47
	console.log("enter   " + this.parser.ruleNames[ctx.ruleIndex] + ", LT(1)=" + 
	                                                  ^
TypeError: Cannot read property 'ruleIndex' of undefined
    at TraceListener.enterEveryRule (/Users/ben/Code/gc-parser/js/src/antlr4/Parser.js:47:52)
    at /Users/ben/Code/gc-parser/js/src/antlr4/Parser.js:254:13
    at Array.map (native)
    at CSVParser.Parser.triggerEnterRuleEvent (/Users/ben/Code/gc-parser/js/src/antlr4/Parser.js:253:24)
    at CSVParser.Parser.enterRule (/Users/ben/Code/gc-parser/js/src/antlr4/Parser.js:436:8)
    at CSVParser.file (/Users/ben/Code/gc-parser/js/csv/CSVParser.js:113:10)
    at Object.<anonymous> (/Users/ben/Code/gc-parser/js/csv/test.js:12:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

**Comment by ericvergnaud** [comment]
Now fixed I believe

**Comment by benself** [comment]
confirmed fixed.  thank you.
