### ISSUE TITLE
#21 not resolved

### ISSUE THREAD

**Issue by benself** [antlr/antlr4-javascript#22]
```
src/antlr4/Parser.js:47
	console.log("enter   " + this.parser.ruleNames[ctx.ruleIndex] + ", LT(1)=" + 
	                                                  ^
TypeError: Cannot read property 'ruleIndex' of undefined
    at TraceListener.enterEveryRule (/Users/ben/Code/gc-parser/js/src/antlr4/Parser.js:47:52)
    at /Users/ben/Code/gc-parser/js/src/antlr4/Parser.js:254:13
    at Array.map (native)
    at CSVParser.Parser.triggerEnterRuleEvent (/Users/ben/Code/gc-parser/js/src/antlr4/Parser.js:253:24)
    at CSVParser.Parser.enterRule (/Users/ben/Code/gc-parser/js/src/antlr4/Parser.js:436:8)
    at CSVParser.file (/Users/ben/Code/gc-parser/js/csv/CSVParser.js:113:10)
    at Object.<anonymous> (/Users/ben/Code/gc-parser/js/csv/test.js:12:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

**Comment by benself** [comment]
This isn't a huge priority, but it is so much harder to debug the JS than the Java.  I appreciate your looking at this.  And I am willing to submit the bugs as I find them, if you are willing to look at them.
